version: "3.8"
services:
  node:
    image: tanguynicolas/instakilo-node
    pull_policy: build
    container_name: instakilo-node
    networks:
      - instakilo-network

  nginx:
    image: tanguynicolas/instakilo-nginx
    pull_policy: build
    container_name: instakilo-nginx
    ports:
      - "80:80"
    networks:
      - instakilo-network
    depends_on:
      - node

networks:
  instakilo-network:

