name: Docker Image CI & CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push node image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/nodejs"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/instakilo-node:latest
          
      - name: Build and push nginx image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:/nginx"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/instakilo-nginx:latest

  run:
    needs: build
    runs-on: ubuntu-latest
    env:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USER }}
      private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      passphrase: ${{ secrets.SSH_PASSPHRASE }}
      port: ${{ secrets.SSH_PORT }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "compose-pull_remote.yaml"
          target: "compose-pull_remote.yaml"
