name: Build and Deploy
on:
  push:
    branches: [ 'main' ]
    
jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SSH setup
        env:
          DEPLOY_KEY: ${{secrets.SSHKEY_RASPBERRY}}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          SERVER_IP: ${{secrets.IP_RASPBERRY}}
          RSYNC_USER: 'rpi'
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
          echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
          chmod -R 700 ~/.ssh        
      - name: Rsync deployment
        run: |
          rsync -avz -e 'ssh -p 24680' --delete public/ ${RSYNC_USER}@${{secrets.IP_RASPBERRY}}:/var/www/
